## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
unique_values = application_df.nunique()
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
binning_values = application_df["APPLICATION_TYPE"].value_counts()
binning_values

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff = 500
binning_values = application_df["APPLICATION_TYPE"].value_counts()
application_types_to_replace = list(binning_values[binning_values < cutoff].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
classification_values = application_df['CLASSIFICATION'].value_counts()
classification_values

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
classification_values_gt1 = classification_values[classification_values > 1]
classification_values_gt1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff = 700

classification_values = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = list(classification_values[classification_values < cutoff].index)

# Checking empty classifications_to_replace if exists & replace in dataframe
if classifications_to_replace:
    for cls in classifications_to_replace:
        application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [18]:
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [20]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df)
application_df.head(5)

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [22]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(columns=["IS_SUCCESSFUL"]).values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, stratify = y)

In [23]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [30]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 40
hidden_nodes_layer3 = 20
hidden_nodes_layer4 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 50)                2250

 dense_9 (Dense)             (None, 40)                2040

 dense_10 (Dense)            (None, 20)                820

 dense_11 (Dense)            (None, 1)                 21

=================================================================
Total params: 5131 (20.04 KB)
Trainable params: 5131 (20.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [31]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [32]:
callback_points = ModelCheckpoint(filepath='model_weights.weights.h5',
                                      save_weights_only=True,
                                      save_freq=5,
                                      verbose=1)

In [33]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5723 - accuracy: 0.7208
Epoch 2/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5529 - accuracy: 0.7311
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7326
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7339
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7345
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7341
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7351
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7352
Epoch 9/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5449 - accuracy: 0.7350
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7355
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7356
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7364
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7365
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7359
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7367
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7366
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7371
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7374
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7378
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7376
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7383
Epoch 22/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5406 - accuracy: 0.7387
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7388
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7388
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7386
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7385
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7393
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7391
Epoch 29/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7393
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7385
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7400
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7398
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7401
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7400
Epoch 35/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5378 - accuracy: 0.7404
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7391
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7388
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7392
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7400
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7393
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7400
Epoch 42/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5370 - accuracy: 0.7402
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7405
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7392
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7398
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7408
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7412
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7405
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7404

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5556 - accuracy: 0.7261 - 555ms/epoch - 2ms/step
Loss: 0.5556296706199646, Accuracy: 0.726064145565033

In [35]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetsoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [36]:
# Download HD5 file
from google.colab import files
files.download("AlphabetsoupCharity_Optimization.h5")